### ISSUE TITLE
tx value in output: number instead buffer

### ISSUE THREAD

**Issue by fanatid** [mappum/bitcoin-protocol#10]
https://github.com/mappum/bitcoin-protocol/blob/12e07d237c93af6f5cdadac62c23245be2e80c20/src/messages.js#L50
It can be represented in Number: `21*1e6*1e8 < Number.MAX_SAFE_INTEGER` => `2100000000000000 < 9007199254740991`

**Comment by mappum** [comment]
Even though the value fits in 53 bits, I wouldn't like to do it because   of JS floating point arithmetic. This won't happen for some things like addition and subtraction, but it would for division and would leave room for errors in calculations.

**Comment by fanatid** [comment]
On serialization you can check that value has float part and if so, throw error.

**Comment by mappum** [comment]
That still leaves small room for error, and since we are dealing with monetary calculations we have to be extra careful.

**Comment by fanatid** [comment]
ok, than what you think about utility function for conversion from buffer8 to number?

**Comment by mappum** [comment]
Sure, that could be useful and not prone to error. Would you just set it as
a new property on each Buffer8? Named `getNumber()`.

**Comment by fanatid** [comment]
yea, it will be nice, should I create PR?

**Comment by mappum** [comment]
Sure 👍 You'll probably have to create a new Buffer8 type in dataTypes.js
which sets the method property after decode.

**Comment by fanatid** [comment]
hmm, what about set buffer8 from number? for encoding. How I can do this?

**Comment by mappum** [comment]
We could just expose a helper function which takes a number and returns a Buffer. We might actually want the decode one to be a helper function as well to match. Something like `bp.toAmount(n)`, `bp.fromAmount(buf)`. As you mentioned, the encoder should ensure there is no fractional part of the number.

**Comment by mappum** [comment]
Or maybe `numberToAmount` and `amountToNumber` is better.

**Comment by fanatid** [comment]
value should be decoded with [indutny/bn.js](https://github.com/indutny/bn.js)

**Comment by mappum** [comment]
>value should be decoded with indutny/bn.js

I don't like the fact that this forces a dependency on `bn.js` and its API. I like the freedom a Buffer gives so that the consumer can choose their own BN lib. This library really is meant to be just a low-level protocol bytes<->JS object converter, which is why we use simple objects rather than BitcoinJS `Blocks` and `Transactions`.

In practice for Webcoin, we have a transform stream in `bitcoin-net` that covnverts to/from the higher level structures (BitcoinJS `Blocks`, etc.), and I think it makes sense to do the BN.js conversion in this place too.
