### ISSUE TITLE
Not working with bitcoind 0.14?

### ISSUE THREAD

**Issue by jnordberg** [mappum/bitcoin-protocol#74]
I was unable to get the example up and running, the data is sent to the node but no response data is emitted on the stream.

Running the integration tests have a similar result

```
$ npm run test-integration                                                                                                                   130 ↵

> bitcoin-protocol@3.0.1 test-integration /Users/jnordberg/Development/bitcoin-protocol
> tape test/integration/*.js | faucet

✓ Integration with bitcoin core in regtest mode
⨯ spawn process
  not ok 1 should be equivalent
    ---
      operator: deepEqual
      expected: |-
        null
      actual: |-
        { [Error: Loading wallet...] code: -28 }
      at: IncomingMessage.<anonymous> (/Users/jnordberg/Development/bitcoin-protocol/node_modules/bitcoin/lib/jsonrpc.js:127:15)
    ...
✓ handshake
# send ping -> wait pong
  ok 19 correct payload
```

Just hangs indefinitely waiting for a response.

```
$ bitcoind -version
Bitcoin Core Daemon version v0.14.99.0-cf5782508
```
```
$ node --version
v7.9.0
```

**Comment by mappum** [comment]
Really I had just chosen a poor example. Bitcoin nodes will not accept any messages until you first send a `version` message as a handshake. I've updated the example to send a `version` instead of a `ping`.

I also think you may want to use the higher-level module built on top of this one, [bitcoin-net](https://github.com/mappum/bitcoin-net/), since that handles the handshake and other things for you.

As for the integration test error, I'll look into that but it is unrelated to the example not working.

**Comment by jnordberg** [comment]
Ah, that explains it. New example works fine.

I'm trying to get the unconfirmed transactions to create a self-hosted version of [blockchain.info's websocket api](https://blockchain.info/api/api_websocket) that does not require you to run a full node, starting to think now that it might a bit more complicated than connecting to a node and sending a "turn on the firehose" command 😄.

Anyways... thanks a bunch for the response! Cheers!

**Comment by mappum** [comment]
Actually that should be pretty simple, unfortunately my docs just make it seem over-complicated.

This should do what you want:
```js
const { PeerGroup } = require('bitcoin-net')
const Inventory = require('bitcoin-inventory')
// use bitcoin network, could also be swapped out w/ 'webcoin-bitcoin-testnet'
const params = require('webcoin-bitcoin')

let peers = PeerGroup(params.net, { 
  peerOpts: { relay: true } // tell peers to relay all txs to us
})
let inv = Inventory(peers)

inv.on('tx', (tx) => console.log(tx))
peers.connect()
 ```

But remember there isn't much security here since it doesn't verify anything. If a node knew you were doing this, they could spam you with a ton of fake transactions (although I suppose rate-limiting could help, as well as a heuristic which ensures the transaction came from more than one peer).
